server:
  port: 8761

# id приложения
spring:
  application:
    name: discovery-server

eureka:
  client:
    # отключаем default настройки клиентов у сервера (регистрация веб сервисов и пр.)
    register-with-eureka: false
    fetch-registry: false
    # url куда будет происходить регистрация микросервисов
    service-url:
      defaultZone: http://localhost:8761/eureka
    # вкл. проверки работоспособности
    healthcheck:
      enabled: true

# Spring Actuator - для того чтобы не было конфликта у name_app_info id выше должно отличаться от имени project
info:
  application:
    name: @project.name@
    version: @project.version@

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, health-component, info, beans, metrics
  endpoint:
    health:
      show-details: always

# отключение лишних логов
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF